# Generated by Django 5.0.4 on 2024-05-02 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_chapter', models.IntegerField()),
                ('current_lesson', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('journey_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.journeymap')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AS', 'User_Submission'), ('EX', 'Exercise')], max_length=2)),
                ('content', models.CharField(max_length=5000)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.chapter')),
            ],
        ),
    ]
