# Generated by Django 5.0.4 on 2024-05-06 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_chapter2_lesson2_student_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson2',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='journeymap',
            name='student',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='journey_map',
        ),
        migrations.AlterField(
            model_name='student',
            name='current_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.lesson'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.lesson'),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='type',
        ),
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.CharField(default='Lorem ipsum', max_length=5000),
        ),
        migrations.AddField(
            model_name='lesson',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='Title', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
        migrations.DeleteModel(
            name='Chapter2',
        ),
        migrations.DeleteModel(
            name='JourneyMap',
        ),
        migrations.DeleteModel(
            name='Lesson2',
        ),
    ]
