# Generated by Django 5.0.4 on 2024-05-06 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_remove_lesson2_chapter_remove_journeymap_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.chapter'),
            preserve_default=False,
        ),
    ]
