# Generated by Django 5.0.4 on 2024-05-08 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_remove_student_current_chapter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
