# Generated by Django 5.0.4 on 2024-05-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_1', models.IntegerField(blank=True, null=True)),
                ('string_1', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
