# Generated by Django 5.0.4 on 2024-05-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_alter_student_current_lesson_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='chapter',
            new_name='in_chapter',
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('in_chapter', 'number')},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.CharField(default='dolor sit amet', max_length=5000),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='Lesson title', max_length=200),
        ),
    ]
